/**
 * ═══════════════════════════════════════════════════════════════
 * Etherfuse Ramp API Integration — CETES on Stellar
 * ═══════════════════════════════════════════════════════════════
 *
 * Etherfuse is a fiat on/off ramp for Mexico (SPEI ↔ CETES).
 * CETES = Mexican Federal Treasury Certificates (stablebonds).
 *
 * IMPORTANT: The supported digital asset is CETES (not MXNe).
 *   - Testnet issuer: GC3CW7EDYRTWQ635VDIGY6S4ZUF5L6TQ7AA4MWS7LEQDBLUSZXV7UPS4
 *   - Mainnet issuer: (same or see Stellar Expert)
 *
 * API Documentation: https://docs.etherfuse.com
 *
 * Sandbox Environment:
 *   - Account: devnet.etherfuse.com
 *   - API URL: https://api.sand.etherfuse.com
 *   - Networks: Stellar Testnet, Solana Devnet
 *   - Uses fake KYC data & testnet tokens
 *
 * Production Environment:
 *   - Account: app.etherfuse.com
 *   - API URL: https://api.etherfuse.com
 *   - Networks: Stellar Mainnet, Solana Mainnet
 *   - Requires real KYC & approval
 *
 * Authentication:
 *   - Header: Authorization: your-api-key-here
 *   - NO "Bearer" prefix
 *
 * Reference implementation:
 *   https://github.com/ElliotFriend/regional-starter-pack/blob/main/src/lib/anchors/etherfuse
 */

const ETHERFUSE_API_BASE = process.env.NEXT_PUBLIC_ETHERFUSE_API_URL || 'https://api.sand.etherfuse.com';
const ETHERFUSE_API_KEY = process.env.NEXT_PUBLIC_ETHERFUSE_API_KEY;

// ─── CETES Asset on Stellar ─────────────────────────────────────────
// This issuer exists on BOTH testnet and mainnet!
export const CETES_ASSET = {
    code: 'CETES',
    name: 'Etherfuse CETES',
    issuer: 'GC3CW7EDYRTWQ635VDIGY6S4ZUF5L6TQ7AA4MWS7LEQDBLUSZXV7UPS4',
    description: 'Mexican Federal Treasury Certificates — short-term government bonds tokenized by Etherfuse.',
} as const;

// ─── Types ───────────────────────────────────────────────────────

interface GenerateOnboardingUrlParams {
    customerId: string;
    bankAccountId: string;
    publicKey: string;
    blockchain: 'stellar' | 'solana' | 'base' | 'polygon' | 'monad';
}

interface EtherfuseApiResponse<T> {
    success: boolean;
    data?: T;
    error?: string;
}

// ─── API Functions ───────────────────────────────────────────────

/**
 * Generate onboarding URL for Etherfuse ramp (KYC + bank account linking).
 * Customer has 15 minutes to complete the onboarding process.
 *
 * Both customerId and bankAccountId must be UUIDs generated by us.
 * Etherfuse creates the customer and bank account records on their side.
 */
export async function generateOnboardingUrl(
    params: GenerateOnboardingUrlParams
): Promise<EtherfuseApiResponse<{ url: string; expiresAt: string }>> {
    if (!ETHERFUSE_API_KEY) {
        return {
            success: false,
            error: 'Etherfuse API key not configured. Set NEXT_PUBLIC_ETHERFUSE_API_KEY environment variable.'
        };
    }

    try {
        const response = await fetch(`${ETHERFUSE_API_BASE}/ramp/onboarding-url`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': ETHERFUSE_API_KEY // NO Bearer prefix per docs
            },
            body: JSON.stringify({
                customerId: params.customerId,
                bankAccountId: params.bankAccountId,
                publicKey: params.publicKey,
                blockchain: params.blockchain,
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            let errorMsg = `HTTP ${response.status}: ${response.statusText}`;
            try {
                const errorData = JSON.parse(errorText);
                errorMsg = errorData.error?.message || errorData.message || errorMsg;
            } catch { /* not JSON */ }
            return { success: false, error: errorMsg };
        }

        const data = await response.json();
        return {
            success: true,
            data: {
                // Etherfuse API returns 'presigned_url' per their docs
                url: data.presigned_url || data.url,
                expiresAt: data.expires_at || new Date(Date.now() + 15 * 60 * 1000).toISOString()
            }
        };
    } catch (err) {
        return {
            success: false,
            error: err instanceof Error ? err.message : 'Failed to generate onboarding URL'
        };
    }
}

/**
 * Get a quote for MXN → CETES conversion.
 */
export async function getQuote(
    customerId: string,
    amount: string,
    direction: 'onramp' | 'offramp' = 'onramp',
    wallet: string = ''
): Promise<EtherfuseApiResponse<{
    quoteId: string;
    sourceAmount: string;
    destinationAmount: string;
    exchangeRate: string;
    expiresAt: string;
}>> {
    if (!ETHERFUSE_API_KEY) {
        return { success: false, error: 'Etherfuse API key not configured' };
    }

    try {
        // First, resolve the CETES asset identifier
        const assetsRes = await fetch(`${ETHERFUSE_API_BASE}/ramp/assets?blockchain=stellar&currency=mxn&wallet=${wallet}`, {
            headers: { 'Authorization': ETHERFUSE_API_KEY }
        });
        
        let cetesIdentifier = `CETES:${CETES_ASSET.issuer}`;
        if (assetsRes.ok) {
            const assetsData = await assetsRes.json();
            const cetesAsset = assetsData.assets?.find((a: any) => a.symbol === 'CETES');
            if (cetesAsset?.identifier) {
                cetesIdentifier = cetesAsset.identifier;
            }
        }

        const quoteId = crypto.randomUUID();
        const quoteAssets = direction === 'onramp'
            ? { type: 'onramp', sourceAsset: 'MXN', targetAsset: cetesIdentifier }
            : { type: 'offramp', sourceAsset: cetesIdentifier, targetAsset: 'MXN' };

        const response = await fetch(`${ETHERFUSE_API_BASE}/ramp/quote`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': ETHERFUSE_API_KEY
            },
            body: JSON.stringify({
                quoteId,
                customerId,
                blockchain: 'stellar',
                quoteAssets,
                sourceAmount: amount,
            })
        });

        if (!response.ok) {
            const error = await response.json().catch(() => ({ message: 'Unknown error' }));
            return { success: false, error: error.message || `Quote failed: HTTP ${response.status}` };
        }

        const data = await response.json();
        return {
            success: true,
            data: {
                quoteId: data.quoteId,
                sourceAmount: data.sourceAmount,
                destinationAmount: data.destinationAmountAfterFee || data.destinationAmount,
                exchangeRate: data.exchangeRate,
                expiresAt: data.expiresAt,
            }
        };
    } catch (err) {
        return {
            success: false,
            error: err instanceof Error ? err.message : 'Failed to get quote'
        };
    }
}

/**
 * Create an on-ramp order (MXN → CETES). Returns SPEI payment instructions.
 */
export async function createOnRampOrder(
    bankAccountId: string,
    publicKey: string,
    quoteId: string,
): Promise<EtherfuseApiResponse<{
    orderId: string;
    clabe: string;
    depositAmount: string;
}>> {
    if (!ETHERFUSE_API_KEY) {
        return { success: false, error: 'Etherfuse API key not configured' };
    }

    try {
        const orderId = crypto.randomUUID();
        const response = await fetch(`${ETHERFUSE_API_BASE}/ramp/order`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': ETHERFUSE_API_KEY
            },
            body: JSON.stringify({
                orderId,
                bankAccountId,
                publicKey,
                quoteId,
            })
        });

        if (!response.ok) {
            const error = await response.json().catch(() => ({ message: 'Unknown error' }));
            return { success: false, error: error.message || `Order failed: HTTP ${response.status}` };
        }

        const data = await response.json();
        return {
            success: true,
            data: {
                orderId: data.onramp?.orderId || orderId,
                clabe: data.onramp?.depositClabe || '',
                depositAmount: data.onramp?.depositAmount || '',
            }
        };
    } catch (err) {
        return {
            success: false,
            error: err instanceof Error ? err.message : 'Failed to create on-ramp order'
        };
    }
}

/**
 * Get customer KYC status.
 */
export async function getKycStatus(
    customerId: string,
    publicKey: string,
): Promise<EtherfuseApiResponse<{ status: string }>> {
    if (!ETHERFUSE_API_KEY) {
        return { success: false, error: 'Etherfuse API key not configured' };
    }

    try {
        const response = await fetch(
            `${ETHERFUSE_API_BASE}/ramp/customer/${customerId}/kyc?pubkey=${publicKey}`,
            { headers: { 'Authorization': ETHERFUSE_API_KEY } }
        );

        if (!response.ok) {
            return { success: false, error: `KYC check failed: HTTP ${response.status}` };
        }

        const data = await response.json();
        return { success: true, data: { status: data.status || 'not_started' } };
    } catch (err) {
        return {
            success: false,
            error: err instanceof Error ? err.message : 'Failed to check KYC status'
        };
    }
}

/**
 * Get order status by order ID.
 */
export async function getOrderStatus(
    orderId: string,
): Promise<EtherfuseApiResponse<{
    status: string;
    txHash?: string;
    amountInFiat?: string;
    amountInTokens?: string;
}>> {
    if (!ETHERFUSE_API_KEY) {
        return { success: false, error: 'Etherfuse API key not configured' };
    }

    try {
        const response = await fetch(
            `${ETHERFUSE_API_BASE}/ramp/order/${orderId}`,
            { headers: { 'Authorization': ETHERFUSE_API_KEY } }
        );

        if (!response.ok) {
            return { success: false, error: `Order status failed: HTTP ${response.status}` };
        }

        const data = await response.json();
        return {
            success: true,
            data: {
                status: data.status,
                txHash: data.confirmedTxSignature,
                amountInFiat: data.amountInFiat,
                amountInTokens: data.amountInTokens,
            }
        };
    } catch (err) {
        return {
            success: false,
            error: err instanceof Error ? err.message : 'Failed to check order status'
        };
    }
}

// ─── Utility Functions ───────────────────────────────────────────

/**
 * Generate a UUID v4 for use as customerId or bankAccountId.
 * The Etherfuse API requires proper UUIDs.
 */
export function generateUUID(): string {
    return crypto.randomUUID();
}

/**
 * Get or create persistent customer/bank IDs for a wallet address.
 * Stores in localStorage so the same wallet always maps to the same customer.
 */
export function getOrCreateCustomerIds(walletAddress: string): {
    customerId: string;
    bankAccountId: string;
} {
    const storageKey = `nirium-etherfuse-customer-${walletAddress}`;
    
    if (typeof window !== 'undefined') {
        const stored = localStorage.getItem(storageKey);
        if (stored) {
            try {
                return JSON.parse(stored);
            } catch { /* regenerate */ }
        }
    }

    const ids = {
        customerId: crypto.randomUUID(),
        bankAccountId: crypto.randomUUID(),
    };

    if (typeof window !== 'undefined') {
        localStorage.setItem(storageKey, JSON.stringify(ids));
    }

    return ids;
}
